name: Will Washburn
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
